apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ogh41a4rc-dotnet-basic
  janus-idp.io/tekton: ogh41a4rc-dotnet-basic
  backstage.io/kubernetes-id: ogh41a4rc-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ogh41a4rc-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
